import { HouseParams, wallHeightFt, roofRiseFt, frontBayXs } from "./houseParams";

/**
 * Generates a Blender (bpy) script that rebuilds the designed house as a
 * massing model with materials, sun, and camera — ready for a Cycles
 * render or for refinement via the Blender MCP workflow in blender-setup/.
 */
export function blenderScript(p: HouseParams, style: string): string {
  const wallH = wallHeightFt(p);
  const rise = roofRiseFt(p);
  const bays = frontBayXs(p);
  const json = JSON.stringify(
    {
      width_ft: p.widthFt,
      depth_ft: p.depthFt,
      wall_height_ft: wallH,
      foundation_ft: p.foundationExposedFt,
      roof_shape: p.roofShape,
      roof_rise_ft: rise,
      facade_color: p.facadeColor,
      trim_color: p.trimColor,
      roof_color: p.roofColor,
      shutter_color: p.shutterColor,
      door_color: p.doorColor,
      shutters: p.shutters,
      window_w_ft: p.windowW,
      window_h_ft: p.windowH,
      bay_xs: bays,
      first_floor_ft: p.firstFloorFt,
      garage: p.garage,
      garage_w_ft: p.garageWFt,
      garage_d_ft: p.garageDFt,
      chimney: p.chimney,
      style,
    },
    null,
    2
  );

  return `# Colonial Model 1 — ${style} colonial massing for Blender
# Generated by SiteCommand Colonial Home Designer.
#
# Run inside Blender:  blender --python this_file.py
# or paste into the Scripting workspace and press Run.
# Pairs with the imperial-units setup in blender-setup/.

import bpy
import json
import math

PARAMS = json.loads(r"""${json}""")

FT = 0.3048  # model in meters, dimensions authored in feet


def f(v):
    return float(v) * FT


def hex_to_rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i : i + 2], 16) / 255.0 for i in (0, 2, 4)) + (1.0,)


def material(name, color_hex, roughness=0.8, metallic=0.0):
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes["Principled BSDF"]
    bsdf.inputs["Base Color"].default_value = hex_to_rgb(color_hex)
    bsdf.inputs["Roughness"].default_value = roughness
    bsdf.inputs["Metallic"].default_value = metallic
    return mat


def box(name, w, h, d, x, y, z, mat):
    """w along x, d along y (depth), h along z (up); x,y,z = center."""
    bpy.ops.mesh.primitive_cube_add(size=1, location=(x, y, z))
    ob = bpy.context.object
    ob.name = name
    ob.scale = (w / 2, d / 2, h / 2)
    ob.data.materials.append(mat)
    return ob


def gable(name, w, d, rise, x, y, z, mat, ridge_axis="x"):
    """Closed gable prism; z = elevation of the eave plane."""
    verts = [
        (-w / 2, -d / 2, 0), (w / 2, -d / 2, 0),
        (w / 2, d / 2, 0), (-w / 2, d / 2, 0),
        (-w / 2, 0, rise), (w / 2, 0, rise),
    ]
    faces = [(0, 1, 2, 3), (0, 1, 5, 4), (3, 2, 5, 4), (0, 4, 3), (1, 2, 5)]
    mesh = bpy.data.meshes.new(name)
    mesh.from_pydata(verts, [], faces)
    mesh.update()
    ob = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(ob)
    ob.location = (x, y, z)
    if ridge_axis == "y":
        ob.rotation_euler = (0, 0, math.pi / 2)
    ob.data.materials.append(mat)
    return ob


# ── reset scene ─────────────────────────────────────────────────
bpy.ops.object.select_all(action="SELECT")
bpy.ops.object.delete()

facade = material("Facade", PARAMS["facade_color"])
trim = material("Trim", PARAMS["trim_color"], roughness=0.6)
roof = material("Roof", PARAMS["roof_color"], roughness=0.9)
glass = material("Glass", "#9fbcc8", roughness=0.05, metallic=0.4)
door_m = material("Door", PARAMS["door_color"], roughness=0.5)
shutter = material("Shutter", PARAMS["shutter_color"], roughness=0.7)
ground_m = material("Ground", "#b9c4a0")
fnd_m = material("Foundation", "#b5ab97")

W = f(PARAMS["width_ft"])
D = f(PARAMS["depth_ft"])
WH = f(PARAMS["wall_height_ft"])
FND = f(PARAMS["foundation_ft"])
RISE = f(PARAMS["roof_rise_ft"])
front_y = -D / 2  # front of house faces -y

# ground
bpy.ops.mesh.primitive_plane_add(size=120, location=(0, 0, 0))
bpy.context.object.data.materials.append(ground_m)

# foundation + body
box("Foundation", W + 0.2, FND, D + 0.2, 0, 0, FND / 2, fnd_m)
box("Body", W, WH, D, 0, 0, FND + WH / 2, facade)

# roof
if PARAMS["roof_shape"] == "hip":
    # approximate hip with a shortened-ridge gable pair; fine for massing
    gable("Roof", W, D + f(2), RISE * 0.92, 0, 0, FND + WH, roof)
else:
    gable("Roof", W + f(1.6), D + f(2), RISE, 0, 0, FND + WH, roof)

# windows + shutters on the front facade
ww, wh = f(PARAMS["window_w_ft"]), f(PARAMS["window_h_ft"])
z1 = FND + f(2.8) + wh / 2
z2 = FND + f(PARAMS["first_floor_ft"]) + f(3.2) + wh / 2
for i, bx in enumerate(PARAMS["bay_xs"]):
    x = f(bx)
    box("Win2-%d" % i, ww, wh * 0.9, 0.06, x, front_y - 0.04, z2, glass)
    if PARAMS["shutters"]:
        box("Sh2L-%d" % i, ww * 0.45, wh * 0.9, 0.05, x - ww * 0.78, front_y - 0.04, z2, shutter)
        box("Sh2R-%d" % i, ww * 0.45, wh * 0.9, 0.05, x + ww * 0.78, front_y - 0.04, z2, shutter)
    if i == len(PARAMS["bay_xs"]) // 2:
        continue  # door bay
    box("Win1-%d" % i, ww, wh, 0.06, x, front_y - 0.04, z1, glass)
    if PARAMS["shutters"]:
        box("Sh1L-%d" % i, ww * 0.45, wh, 0.05, x - ww * 0.78, front_y - 0.04, z1, shutter)
        box("Sh1R-%d" % i, ww * 0.45, wh, 0.05, x + ww * 0.78, front_y - 0.04, z1, shutter)

# front door
box("DoorSurround", f(5), f(8), 0.05, 0, front_y - 0.03, FND + f(4), trim)
box("Door", f(3.2), f(6.9), 0.08, 0, front_y - 0.06, FND + f(3.45), door_m)

# garage
if PARAMS["garage"] != "none":
    gw, gd = f(PARAMS["garage_w_ft"]), f(PARAMS["garage_d_ft"])
    gh = f(PARAMS["first_floor_ft"]) + f(2)
    g_rise = f(PARAMS["garage_w_ft"] / 2 * 8 / 12)  # 8/12 garage pitch
    if PARAMS["garage"] == "front2":
        gx, gy = W / 2 + gw / 2, front_y + gd / 2
        box("Garage", gw, gh, gd, gx, gy, FND + gh / 2, facade)
        # ridge points to the street: ridge length = depth, span = width
        gable("GarageRoof", gd + f(1.6), gw + f(1.6), g_rise, gx, gy, FND + gh, roof, ridge_axis="y")
    else:
        gx = W / 2 + gd / 2 + (f(8) if PARAMS["garage"] == "detached2" else 0)
        box("Garage", gd, gh, gw, gx, 0, FND + gh / 2, facade)
        gable("GarageRoof", gd + f(1.6), gw + f(1.6), g_rise, gx, 0, FND + gh, roof)

# chimney
if PARAMS["chimney"]:
    ch = FND + WH + RISE + f(3)
    box("Chimney", f(2.2), ch, f(2.2), W / 2 - f(6), 0, ch / 2, material("Brick", "#8a4434"))

# ── light + camera + render settings ────────────────────────────
bpy.ops.object.light_add(type="SUN", location=(20, -18, 28))
sun = bpy.context.object
sun.data.energy = 4.0
sun.rotation_euler = (math.radians(50), math.radians(-12), math.radians(35))

cam_dist = max(W, D) * 2.1
bpy.ops.object.camera_add(
    location=(cam_dist * 0.72, -cam_dist * 0.8, FND + WH * 0.9),
    rotation=(math.radians(78), 0, math.radians(42)),
)
bpy.context.scene.camera = bpy.context.object

scene = bpy.context.scene
scene.render.engine = "CYCLES"
scene.cycles.samples = 128
scene.render.resolution_x = 1920
scene.render.resolution_y = 1280

print("Colonial Model 1 massing built — press F12 to render.")
`;
}
