import { QuizAnswers } from "../types/quiz";
import { COLONIAL_MODEL_1 } from "../data/colonialModel1";
import { HouseParams, wallHeightFt } from "./houseParams";

/**
 * Generates the Revit package: a machine-readable parameter file plus a
 * pyRevit script that rebuilds the designed house as a native Revit model
 * (levels, walls, floors, footprint roof, doors/windows) so the user ends
 * up with a real .rvt and can sheet it from there.
 */

export function houseParamsJson(
  params: HouseParams,
  answers: QuizAnswers,
  style: string,
  budget: string
): string {
  // keep uploaded images (data URLs) out of the export — they're huge
  const selections: QuizAnswers = Object.fromEntries(
    Object.entries(answers).map(([k, v]) => [
      k,
      typeof v === "string" && v.startsWith("data:") ? "(uploaded file)" : v,
    ])
  );
  const cleanParams: HouseParams = {
    ...params,
    site: { ...params.site, topoMapUrl: params.site.topoMapUrl ? "(uploaded file)" : null },
  };
  return JSON.stringify(
    {
      generator: "SiteCommand Colonial Home Designer",
      generatedAt: new Date().toISOString(),
      model: "Colonial Model 1",
      architecturalStyle: style,
      budget,
      dimensions: {
        frontFt: COLONIAL_MODEL_1.frontDimension,
        sideFt: COLONIAL_MODEL_1.sideDimension,
        firstFloorSqFt: COLONIAL_MODEL_1.firstFloorSqFt,
        secondFloorSqFt: COLONIAL_MODEL_1.secondFloorSqFt,
        thirdFloorSqFt: COLONIAL_MODEL_1.thirdFloorSqFt,
        totalSqFt: COLONIAL_MODEL_1.totalSqFt,
      },
      parameters: cleanParams,
      selections,
    },
    null,
    2
  );
}

export function pyRevitScript(params: HouseParams, style: string): string {
  const p = params;
  const wallH = wallHeightFt(p);
  const slopeOnAll = p.roofShape === "hip";
  const json = JSON.stringify(
    {
      width_ft: p.widthFt,
      depth_ft: p.depthFt,
      first_floor_ft: p.firstFloorFt,
      second_floor_ft: p.secondFloorFt,
      wall_height_ft: wallH,
      roof_shape: p.roofShape,
      roof_pitch: p.roofPitch,
      bays: p.bays,
      window_w_ft: p.windowW,
      window_h_ft: p.windowH,
      sill_ft: 2.8,
      garage: p.garage,
      garage_w_ft: p.garageWFt,
      garage_d_ft: p.garageDFt,
      style,
    },
    null,
    2
  );

  return `# -*- coding: utf-8 -*-
"""Colonial Model 1 — ${style} colonial
Generated by SiteCommand Colonial Home Designer.

HOW TO RUN
  1. Open Revit (2022 or newer) with a new project from your
     architectural template.
  2. Install pyRevit (https://github.com/pyrevitlabs/pyRevit) if you
     haven't already.
  3. pyRevit tab -> pyRevit (hamburger) -> "Run pyRevit script",
     pick this file. (RevitPythonShell works too.)

WHAT IT BUILDS
  - Levels: Level 1, Level 2, Roof Plate
  - Exterior walls for both stories (default wall type)
  - Floor slabs at Level 1 and Level 2
  - A footprint roof with the correct pitch (gable or hip)
  - Front door + window grid on the front wall, if the template has
    door/window families loaded
  - Attached garage walls when one was selected

The result is real, editable Revit geometry — swap wall/window types,
then create plan/elevation views and sheets as usual. Pair it with the
parameter JSON from the same download for schedules and tagging.
"""

import json
import math
import clr

from Autodesk.Revit.DB import (
    Transaction,
    Line,
    XYZ,
    Level,
    Wall,
    Floor,
    CurveLoop,
    CurveArray,
    FilteredElementCollector,
    BuiltInCategory,
    BuiltInParameter,
    FamilySymbol,
    ElementTypeGroup,
    ModelCurveArray,
    RoofType,
    FloorType,
)
from Autodesk.Revit.DB.Structure import StructuralType

PARAMS = json.loads(r"""${json}""")

doc = __revit__.ActiveUIDocument.Document  # noqa: F821

W = float(PARAMS["width_ft"])
D = float(PARAMS["depth_ft"])
L1_ELEV = 0.0
L2_ELEV = float(PARAMS["first_floor_ft"]) + 1.0
PLATE_ELEV = float(PARAMS["wall_height_ft"])
PITCH = float(PARAMS["roof_pitch"]) / 12.0
HIP = PARAMS["roof_shape"] == "hip"

log = []


def get_or_create_level(name, elevation):
    for lv in FilteredElementCollector(doc).OfClass(Level):
        if abs(lv.Elevation - elevation) < 0.01:
            return lv
    lv = Level.Create(doc, elevation)
    try:
        lv.Name = name
    except Exception:
        pass  # name collision in template; elevation is what matters
    return lv


def rect_points(w, d, cx=0.0, cy=0.0):
    return [
        XYZ(cx - w / 2, cy - d / 2, 0),
        XYZ(cx + w / 2, cy - d / 2, 0),
        XYZ(cx + w / 2, cy + d / 2, 0),
        XYZ(cx - w / 2, cy + d / 2, 0),
    ]


def make_walls(points, level, height):
    walls = []
    wt_id = doc.GetDefaultElementTypeId(ElementTypeGroup.WallType)
    n = len(points)
    for i in range(n):
        a, b = points[i], points[(i + 1) % n]
        line = Line.CreateBound(a, b)
        wall = Wall.Create(doc, line, wt_id, level.Id, height, 0.0, False, False)
        walls.append(wall)
    return walls


def make_floor(points, level):
    loop = CurveLoop()
    n = len(points)
    for i in range(n):
        loop.Append(Line.CreateBound(points[i], points[(i + 1) % n]))
    ft_id = doc.GetDefaultElementTypeId(ElementTypeGroup.FloorType)
    try:
        # Revit 2022+
        from System.Collections.Generic import List

        loops = List[CurveLoop]()
        loops.Add(loop)
        return Floor.Create(doc, loops, ft_id, level.Id)
    except Exception as e:
        log.append("Floor skipped: %s" % e)
        return None


def make_roof(points, level):
    roof_type = None
    for rt in FilteredElementCollector(doc).OfClass(RoofType):
        roof_type = rt
        break
    if roof_type is None:
        log.append("Roof skipped: no RoofType in template")
        return None
    ca = CurveArray()
    n = len(points)
    for i in range(n):
        ca.Append(Line.CreateBound(points[i], points[(i + 1) % n]))
    footprint = clr.Reference[ModelCurveArray]()
    roof = doc.Create.NewFootPrintRoof(ca, level, roof_type, footprint)
    angle = math.atan(PITCH)
    idx = 0
    for mc in footprint.Value:
        # footprint order matches input: 0 = front, 1 = right, 2 = back, 3 = left
        slope = HIP or idx in (0, 2)
        roof.set_DefinesSlope(mc, slope)
        if slope:
            roof.set_SlopeAngle(mc, angle)
        idx += 1
    return roof


def first_symbol(category):
    for sym in (
        FilteredElementCollector(doc)
        .OfCategory(category)
        .OfClass(FamilySymbol)
    ):
        return sym
    return None


def place_hosted(symbol, wall, point, level):
    if not symbol.IsActive:
        symbol.Activate()
        doc.Regenerate()
    return doc.Create.NewFamilyInstance(
        point, symbol, wall, level, StructuralType.NonStructural
    )


t = Transaction(doc, "SiteCommand — build Colonial Model 1")
t.Start()
try:
    l1 = get_or_create_level("Level 1", L1_ELEV)
    l2 = get_or_create_level("Level 2", L2_ELEV)
    plate = get_or_create_level("Roof Plate", PLATE_ELEV)
    log.append("Levels: 0' / %.1f' / %.1f'" % (L2_ELEV, PLATE_ELEV))

    pts = rect_points(W, D)
    walls_l1 = make_walls(pts, l1, L2_ELEV - L1_ELEV)
    walls_l2 = make_walls(pts, l2, PLATE_ELEV - L2_ELEV)
    log.append("Exterior walls: %d" % (len(walls_l1) + len(walls_l2)))

    make_floor(pts, l1)
    make_floor(pts, l2)
    log.append("Floors: Level 1, Level 2")

    if make_roof(pts, plate) is not None:
        log.append("Roof: %s @ %s/12" % (PARAMS["roof_shape"], PARAMS["roof_pitch"]))

    # front wall is the first one created (y = -D/2)
    front_wall = walls_l1[0]
    door_sym = first_symbol(BuiltInCategory.OST_Doors)
    if door_sym is not None:
        try:
            place_hosted(door_sym, front_wall, XYZ(0, -D / 2, L1_ELEV), l1)
            log.append("Front door placed")
        except Exception as e:
            log.append("Door skipped: %s" % e)
    else:
        log.append("Door skipped: no door family loaded")

    win_sym = first_symbol(BuiltInCategory.OST_Windows)
    if win_sym is not None:
        bays = int(PARAMS["bays"])
        margin = 4.5
        span = W - 2 * margin
        sill = float(PARAMS["sill_ft"])
        placed = 0
        for i in range(bays):
            x = -span / 2 + span * i / (bays - 1)
            # second floor: every bay; first floor: skip center (door)
            for lv, z in ((l2, L2_ELEV + sill), (l1, L1_ELEV + sill)):
                if lv is l1 and i == bays // 2:
                    continue
                try:
                    place_hosted(win_sym, front_wall, XYZ(x, -D / 2, z), lv)
                    placed += 1
                except Exception as e:
                    log.append("Window skipped: %s" % e)
        log.append("Windows placed on front wall: %d" % placed)
    else:
        log.append("Windows skipped: no window family loaded")

    if PARAMS["garage"] != "none":
        gw = float(PARAMS["garage_w_ft"])
        gd = float(PARAMS["garage_d_ft"])
        if PARAMS["garage"] == "front2":
            gx, gy = W / 2 + gw / 2, -D / 2 + gd / 2
            g_pts = rect_points(gw, gd, gx, gy)
        else:
            gap = 8.0 if PARAMS["garage"] == "detached2" else 0.0
            gx, gy = W / 2 + gd / 2 + gap, 0.0
            g_pts = rect_points(gd, gw, gx, gy)
        make_walls(g_pts, l1, float(PARAMS["first_floor_ft"]) + 2.0)
        make_floor(g_pts, l1)
        log.append("Garage shell: %s" % PARAMS["garage"])

    t.Commit()
    print("SiteCommand build complete:")
    for line in log:
        print("  - " + line)
except Exception as e:
    t.RollBack()
    print("Build failed and was rolled back: %s" % e)
    for line in log:
        print("  - " + line)
`;
}
